# Generated by Django 4.0.6 on 2022-09-17 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EMails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=125)),
                ('body', models.TextField()),
                ('repeat', models.BooleanField(default=True)),
                ('schedule', models.CharField(choices=[('Monday', 'Mondays'), ('Tuesday', 'Tuesdays'), ('Wednesday', 'Wednesdays'), ('Thursday', 'Thursdays'), ('Friday', 'Fridays'), ('Saturday', 'Saturdays'), ('Sunday', 'Sundays'), ('Everyday', 'Everyday')], max_length=100)),
            ],
        ),
    ]
