# Generated by Django 4.0.6 on 2022-09-22 00:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=125)),
                ('body', models.TextField()),
                ('receiver', models.CharField(choices=[('A', 'Group A'), ('B', 'Group B'), ('C', 'Group C'), ('D', 'Group D')], default=1, max_length=3)),
                ('repeat', models.BooleanField(default=True)),
                ('schedule', models.CharField(choices=[('Monday', 'Mondays'), ('Tuesday', 'Tuesdays'), ('Wednesday', 'Wednesdays'), ('Thursday', 'Thursdays'), ('Friday', 'Fridays'), ('Saturday', 'Saturdays'), ('Sunday', 'Sundays'), ('Everyday', 'Everyday')], default=0, max_length=100)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EMails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=150)),
                ('group', models.CharField(choices=[('A', 'Group A'), ('B', 'Group B'), ('C', 'Group C'), ('D', 'Group D')], default=1, max_length=3)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
