# Generated by Django 4.0.6 on 2022-09-19 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Mailer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emails',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='schedule',
            field=models.CharField(choices=[('Monday', 'Mondays'), ('Tuesday', 'Tuesdays'), ('Wednesday', 'Wednesdays'), ('Thursday', 'Thursdays'), ('Friday', 'Fridays'), ('Saturday', 'Saturdays'), ('Sunday', 'Sundays'), ('Everyday', 'Everyday')], default=0, max_length=100),
        ),
    ]
