# Generated by Django 4.0.6 on 2022-08-16 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_alter_team_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('account_name', models.CharField(max_length=150)),
                ('contact_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=200)),
                ('phone', models.CharField(max_length=11)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.team')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('priority', models.CharField(choices=[('H', 'HIGH'), ('M', 'MEDIUM'), ('L', 'LOW')], max_length=100)),
                ('task_type', models.CharField(choices=[('PHONE', 'PHONE CALL'), ('EMAIL', 'EMAIL'), ('VISIT', 'VISITATION'), ('MEETINGS', 'MEETINGS'), ('PROPOSAL', 'SEND PROPOSAL')], max_length=100)),
                ('description', models.TextField()),
                ('status', models.BooleanField(default=False)),
                ('repeat', models.BooleanField(default=False)),
                ('action_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.lead')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Activitie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('activity_type', models.CharField(choices=[('PHONE', 'PHONE CALL'), ('EMAIL', 'EMAIL'), ('VISIT', 'VISITATION'), ('MEETINGS', 'MEETINGS'), ('PROPOSAL', 'SEND PROPOSAL')], max_length=100)),
                ('description', models.TextField()),
                ('status', models.BooleanField(default=False)),
                ('repeat', models.BooleanField(default=False)),
                ('action_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.lead')),
                ('executor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
