# Generated by Django 4.0.6 on 2022-08-16 12:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_team_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('team_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.team')),
                ('team_members', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            bases=('users.team',),
        ),
    ]
